import gleam/bool
import gleam/int
import gleam/io
import gleam/list
import gleam/order
import gleam/result
import gleam/string
import simplifile

pub fn main() {
  let assert Ok(content) = simplifile.read("priv/huffman_table")
    as "✗ Failed to read priv/huffman_table"

  let entries = parse_huffman_table(content)
  let generated_code = generate_huffman_code(entries)

  let assert Ok(_) =
    simplifile.write("src/alpacki/internal/huffman.gleam", generated_code)
    as "✗ Failed to write generated file"

  io.println("✓ Generated src/alpacki/internal/huffman.gleam")
  Nil
}

type HuffmanEntry {
  HuffmanEntry(symbol: Int, binary: String, hex: String, length: Int)
}

fn parse_huffman_table(content: String) -> List(HuffmanEntry) {
  content
  |> string.split("\n")
  |> list.filter_map(fn(line) {
    case parse_line(line), line {
      Ok(entry), _ -> Ok(entry)
      Error(Nil), "" -> Error(Nil)
      Error(Nil), _ -> panic as { "✗ Failed to parse line: \n  " <> line }
    }
  })
}

fn parse_line(line: String) -> Result(HuffmanEntry, Nil) {
  let trimmed = string.trim(line)
  use <- bool.guard(when: trimmed == "", return: Error(Nil))

  // Extract symbol number from "(  0)" or "' ' ( 32)" or "EOS (256)"
  use #(symbol_part, remaining) <- result.try(case string.split(trimmed, ")") {
    [symbol_part, remaining] | [_special_case, symbol_part, remaining] ->
      Ok(#(
        symbol_part,
        string.split(remaining, "|") |> list.drop(1) |> string.join("|"),
      ))
    _ -> Error(Nil)
  })

  use symbol_string <- result.try(string.split(symbol_part, "(") |> list.last)
  use symbol <- result.try(symbol_string |> string.trim |> int.parse)

  // Parse the rest: "11111111|11000                             1ff8  [13]"
  let tokens =
    string.split(remaining, " ")
    |> list.filter(fn(token) { !string.is_empty(string.trim(token)) })

  use #(binary, hex, length_part) <- result.try(case tokens {
    [binary, hex, length_part] | [binary, hex, _bracket_opening, length_part] ->
      Ok(#(string.replace(binary, "|", ""), hex, length_part))
    _ -> Error(Nil)
  })

  use length <- result.try(
    length_part
    |> string.replace("[", "")
    |> string.replace("]", "")
    |> string.trim
    |> int.parse,
  )

  Ok(HuffmanEntry(symbol:, binary:, hex:, length:))
}

fn generate_huffman_code(entries: List(HuffmanEntry)) -> String {
  let header =
    "// DO NOT EDIT - Generated by dev/generate_huffman.gleam

import gleam/bit_array

"

  let decode_fn = generate_decode_function(entries)
  let encode_fn = generate_encode_function(entries)

  header <> decode_fn <> "\n\n" <> encode_fn <> "\n"
}

fn generate_encode_function(entries: List(HuffmanEntry)) -> String {
  let regular_entries = list.filter(entries, fn(e) { e.symbol < 256 })

  let header =
    "/// Encodes data using Huffman encoding (RFC 7541 Appendix B)
pub fn encode(data: BitArray, accumulated: BitArray) -> BitArray {
  case data {
"

  let cases =
    list.map(regular_entries, fn(entry) {
      let hex_value = "0x" <> entry.hex
      "    <<"
      <> int.to_string(entry.symbol)
      <> ", remaining:bytes>> ->\n"
      <> "      encode(remaining, <<accumulated:bits, "
      <> hex_value
      <> ":"
      <> int.to_string(entry.length)
      <> ">>)"
    })
    |> string.join("\n")

  let footer =
    "    <<>> -> add_eos_padding(accumulated)
    _ -> panic as \"Invalid byte in Huffman encoding input\"
  }
}

// Add EOS padding to align to octet boundary
fn add_eos_padding(accumulated: BitArray) -> BitArray {
  let remainder = bit_array.bit_size(accumulated) % 8
  case remainder {
    0 -> accumulated
    _ -> {
      let bits_to_add = 8 - remainder
      <<accumulated:bits, ones(bits_to_add):size(bits_to_add)>>
    }
  }
}

// Returns N bits of 1s
fn ones(n: Int) -> Int {
  case n {
    1 -> 0b1
    2 -> 0b11
    3 -> 0b111
    4 -> 0b1111
    5 -> 0b11111
    6 -> 0b111111
    7 -> 0b1111111
    _ -> 0
  }
}"

  header <> cases <> "\n" <> footer
}

fn generate_decode_function(entries: List(HuffmanEntry)) -> String {
  // Sort by bit length descending, then by symbol
  let sorted_entries =
    list.sort(entries, fn(a, b) {
      case int.compare(b.length, a.length) {
        order.Eq -> int.compare(a.symbol, b.symbol)
        other -> other
      }
    })

  let header =
    "pub type HuffmanError {
  EOSSymbolInData
  InvalidPadding
}

/// Decodes Huffman-encoded data (RFC 7541 Appendix B)
pub fn decode(
  bits: BitArray,
  accumulated: BitArray,
) -> Result(BitArray, HuffmanError) {
  case bits {
"

  let cases =
    list.map(sorted_entries, fn(entry) {
      let hex_value = "0x" <> entry.hex
      let len = int.to_string(entry.length)

      case entry.symbol {
        256 ->
          "    <<"
          <> hex_value
          <> ":"
          <> len
          <> ", _:bits>> -> Error(EOSSymbolInData)"
        symbol ->
          "    <<"
          <> hex_value
          <> ":"
          <> len
          <> ", remaining:bits>> ->\n"
          <> "      decode(remaining, <<accumulated:bits, "
          <> int.to_string(symbol)
          <> ">>)"
      }
    })
    |> string.join("\n")

  let footer =
    "    <<>> -> Ok(accumulated)
    // Valid EOS padding (1-7 bits, all 1s)
    <<0b1:1>> -> Ok(accumulated)
    <<0b11:2>> -> Ok(accumulated)
    <<0b111:3>> -> Ok(accumulated)
    <<0b1111:4>> -> Ok(accumulated)
    <<0b11111:5>> -> Ok(accumulated)
    <<0b111111:6>> -> Ok(accumulated)
    <<0b1111111:7>> -> Ok(accumulated)
    _ -> Error(InvalidPadding)
  }
}"

  header <> cases <> "\n" <> footer
}
