import gleam/bool
import gleam/int
import gleam/io
import gleam/list
import gleam/result
import gleam/string
import simplifile

pub fn main() {
  let assert Ok(content) = simplifile.read("priv/static_table")
    as "✗ Failed to read priv/static_table"

  let entries = parse_static_table(content)
  let generated_code = generate_static_table_code(entries)

  let assert Ok(_) =
    simplifile.write("src/alpacki/internal/static_table.gleam", generated_code)
    as "✗ Failed to write generated file"

  io.println("✓ Generated src/alpacki/internal/static_table.gleam")
}

type StaticTableEntry {
  StaticTableEntry(index: Int, name: String, value: String)
}

fn parse_static_table(content: String) -> List(StaticTableEntry) {
  content
  |> string.split("\n")
  |> list.filter_map(fn(line) {
    case parse_line(line), line {
      Ok(entry), _ -> Ok(entry)
      Error(Nil), "" -> Error(Nil)
      Error(Nil), line_content ->
        case string.trim(line_content) {
          "" -> Error(Nil)
          _ -> panic as { "✗ Failed to parse line:\n  " <> line_content }
        }
    }
  })
}

fn parse_line(line: String) -> Result(StaticTableEntry, Nil) {
  let trimmed = string.trim(line)
  use <- bool.guard(when: trimmed == "", return: Error(Nil))

  let all_parts =
    string.split(trimmed, "|")
    |> list.map(string.trim)

  use #(index_string, name, value) <- result.try(case all_parts {
    ["", index_string, name, value, ""] -> Ok(#(index_string, name, value))
    _ -> Error(Nil)
  })

  use index <- result.try(int.parse(index_string))

  Ok(StaticTableEntry(index:, name:, value:))
}

fn generate_static_table_code(entries: List(StaticTableEntry)) -> String {
  let header =
    "// DO NOT EDIT - Generated by dev/generate_static_table.gleam
//
// Static table from RFC 7541 Appendix A
// https://www.rfc-editor.org/rfc/rfc7541#appendix-A

/// Result of matching a header against the static table
pub type StaticTableMatch {
  /// Both name and value match exactly
  FullMatch(index: Int)
  /// Only the name matches, with index of first occurrence
  NameMatch(index: Int)
  /// Name not in static table
  NoMatch
}

"

  let lookup_fn = generate_lookup_function(entries)
  let match_fn = generate_match_function(entries)

  header <> lookup_fn <> "\n\n" <> match_fn <> "\n"
}

fn generate_lookup_function(entries: List(StaticTableEntry)) -> String {
  let header =
    "/// Looks up a header by its index (1-61) in the static table.
pub fn lookup(index: Int) -> Result(#(String, String), Nil) {
  case index {
"

  let cases =
    list.map(entries, fn(entry) {
      let name = quote_string(entry.name)
      let value = quote_string(entry.value)
      "    "
      <> int.to_string(entry.index)
      <> " -> Ok(#("
      <> name
      <> ", "
      <> value
      <> "))"
    })
    |> string.join("\n")

  let footer =
    "
    _ -> Error(Nil)
  }
}"

  header <> cases <> footer
}

fn generate_match_function(entries: List(StaticTableEntry)) -> String {
  let unique_entries = unique_by_name(entries)

  let header =
    "/// Matches a header against the static table.
///
/// Returns:
/// - `FullMatch(index)` if both name and value match exactly
/// - `NameMatch(index)` if only the name matches
/// - `NoMatch` if the name is not in the static table
pub fn match(name: String, value: String) -> StaticTableMatch {
  case name, value {
"

  // Generate full match cases (all entries with exact name and value)
  let full_match_cases =
    list.map(entries, fn(entry) {
      let name = quote_string(entry.name)
      let value = quote_string(entry.value)
      "    "
      <> name
      <> ", "
      <> value
      <> " -> FullMatch("
      <> int.to_string(entry.index)
      <> ")"
    })
    |> string.join("\n")

  // Generate name-only match cases (unique names with _ for value)
  let name_match_cases =
    list.map(unique_entries, fn(entry) {
      let name = quote_string(entry.name)
      "    " <> name <> ", _ -> NameMatch(" <> int.to_string(entry.index) <> ")"
    })
    |> string.join("\n")

  let footer =
    "
    _, _ -> NoMatch
  }
}"

  header <> full_match_cases <> "\n" <> name_match_cases <> footer
}

fn quote_string(text: String) -> String {
  let escaped =
    string.replace(text, "\\", "\\\\")
    |> string.replace("\"", "\\\"")
  "\"" <> escaped <> "\""
}

fn unique_by_name(entries: List(StaticTableEntry)) -> List(StaticTableEntry) {
  list.fold(entries, [], fn(acc, entry) {
    let StaticTableEntry(_, entry_name, _) = entry
    let name_exists =
      list.any(acc, fn(existing) {
        let StaticTableEntry(_, existing_name, _) = existing
        existing_name == entry_name
      })
    case name_exists {
      True -> acc
      False -> [entry, ..acc]
    }
  })
  |> list.reverse
}
